name: club
channels:
  - defaults
dependencies:
  - ca-certificates=2021.1.19=haa95532_0
  - certifi=2020.12.5=py37haa95532_0
  - openssl=1.1.1j=h2bbff1b_0
  - pip=21.0.1=py37haa95532_0
  - python=3.7.10=h6244533_0
  - setuptools=52.0.0=py37haa95532_0
  - sqlite=3.33.0=h2a8f88b_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.36.2=pyhd3eb1b0_0
  - wincertstore=0.2=py37_0
  - zlib=1.2.11=h62dcd97_4
  - pip:
      - asgiref==3.3.1
      - django==3.1.7
      - pillow==8.1.2
      - pytz==2021.1
      - sqlparse==0.4.1
prefix: E:\Anaconda\envs\club
